config/routes.rb
Rails.application.routes.draw do
  
  resources :lists, :path => '' do 


  	resources :tasks ,except: [:index]

  	resources :task_temporaries, controller: 'tasks', type: 'TaskTemporary' ,except: [:show,:index]
 	resources :task_longs, controller: 'tasks', type: 'TaskLong' ,except: [:show,:index]
 	resources :task_simples, controller: 'tasks', type: 'TaskSimple' ,except: [:show,:index]
  
  end

  	
  	patch '/finish/task/:id', to: 'tasks#finish'

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	root 'lists#index'
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  url        :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class List < ApplicationRecord
	
	has_many :tasks ,dependent: :destroy
	has_many :task_simples 
	has_many :task_temporaries
	has_many :task_longs
	

	before_create :normalize_name
	before_create :assign_slug

	validates :name, 
		presence: { message: :presence_msj },
		uniqueness: { :case_sensitive =>false ,message: :uniqueness_msj },
		format: { with: /[a-zA-ZñÑáéíóúÁÉÍÓÚ\s]+/,message: :format_msj }

	#validates :url,
	#	uniqueness: { message: :uniqueness_msj}

 	def last_update

 		maxTask=self.tasks.select('updated_at').maximum(:updated_at)
	    unless maxTask.nil?
	        return [maxTask,self.updated_at].max 
	    else
	      return self.updated_at
	    end
	    
 	end

 	def to_param
      url
 	end

 	def update_tasks_expired
 		self.task_temporaries.expired.change_state
 	end

	private
		
		def normalize_name
      		self.name = name.downcase.capitalize
    	end
		
		def assign_slug
		    self.url = name.parameterize
		end
		 

		
end


 

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  include CookieHelper 

  before_action :set_list, only:[:destroy, :update, :show, :edit]
  #cambiar el etado a la tarea expirada y no mostrarla
  before_action :expire_tasks , only:[:show]


  def index
   
    @list= List.new 
    #@lists=List.all
    @lists = List.where(id: lists_browser)

  end

  def show
    @task_simples=@list.task_simples
    @task_temporaries= TaskTemporaryDecorator.decorate_collection( @list.task_temporaries)
    @task_longs=@list.task_longs
   
  end

  def create  	
 
    @list= List.new(list_params)
    
    respond_to do |format|
      if @list.save
         update_cookie
         format.html  {redirect_to @list, notice: 'List was successfully created.' }

      else 
        @lists = List.where(id: lists_browser)
        format.html { render :index }
        format.json { render json: @list.errors, status: :unprocessable_entity } 
      end
    end
  
  end




  def destroy
    id=@list.id
    respond_to do |format|
      if  @list.destroy
          cookie_delete_data(id)
          format.js {}
      else

      end
    end
  
   
  end


  def update 
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json {render json: @list, status: :ok}
        format.js 
      else
        format.js { render 'error-update' }
      end
    end
  end



private


  def set_list

       @list= List.find_by_url(params[:id]) or raise  ActiveRecord::RecordNotFound      
       @list=@list.decorate
    
  end

  def list_params
    params.require(:list).permit(:name)
  end

  def expire_tasks
      @list.update_tasks_expired
  end

  def update_cookie
     id=cookie_add_data(@list.id)
     List.delete(id)
  end

  def stored_maximum
    #metodo usado en CookiesHelper
    #define la cantidad de listas que deberan guardarse
    5
  end


end

app/views/lists/_empty-collection.html.erb
<div class='wow fadeInUp content-card full-width' style='margin-top: 1em;' >
   <div class="orange-text text-darken-2">
   		 <%=t('list-empty') %>
   </div>  
</div>

app/views/lists/_empty_tasks.html.erb
<tr>
	<td></td>
	<td class="orange-text">  <%= t('no-elements')%></td>
</tr>

app/views/lists/_errors.html.erb
 <% if list.errors.any? %>
	<div id="error_explanation" class="card-panel red lighten-5 red-text"">
	  	 <ul>
		   <% list.errors.messages.each do |message| %>
		   <li><%= message %></li>
			<% end %>
      	 </ul>
	 </div>
<% end %>

app/views/lists/_form.html.erb
  <div class="row">
   

      <%= simple_form_for @list  do |f| %>
            
     	 
           <div class="input-field col s12 m6 l8">
      	     <%= f.input :name, label: false,:placeholder => t('list-name'),:inner_html => { id: 'input-text'} %>
           </div>
           <div class="input-field col s12 m6 l4" style="display: flex;" >
           <%=  f.button  :button, t('delete'), :type => 'reset', :class => 'btn'%>
      	   
           <%= f.submit :class => "right waves-effect blue darken-3 btn"%>
        
           </div>

      <% end %>
  </div>

app/views/lists/_list.html.erb
<div id="<%=list.id%>" class="screenshot-item  col s12 m6 l6 contener-texto" >

	<div class="row" style="margin-bottom: 0px">
        <div class="col s12 ">
          <div class="card  darken-1">
            <div class="card-content ">
             <p> <%= list.name %><p>
             <span class="right"></span>
            </div>
            <div class="card-action">
             <span class="chip no-margin" ><%=list.tasks.countOnlyActive%></span>

             <span class="right">
              
               <%= link_to list, method: :delete, data: { confirm:t('confirm') },:remote => true  do %>
                 <%= t('delete')%>
                <% end %>
               
               
               <%= link_to t('view-more'),list %>
             </span>
            
           

            </div>
          </div>
        </div>
      </div>
	 
	 
</div>

app/views/lists/destroy.js.erb
$('#<%=@list.id%>').hide('slow',function(){
	$(this).remove
})

show_success_noty('success', 'Success!');

app/views/lists/error-update.js.erb
 show_success_noty('error','Error')

app/views/lists/index.html.erb
					<div class="wow fadeInUp content-card">
						 
							<div class="icon-and-title-flex">
									<img id='logo' src="<%= image_path('post.it.png')%>" class="appicon"></img>
									
									<div class="title-container ">
							
										<span class="text-title font-pacifico shadow" >Task Management</span>
										<br><div class="intertext-padding"></div>
										
										<span class="text-subtitle"><%= t('subtitle') %></span> 
										<br><div class="intertext-padding"></div>
										
									</div>  
								</div>
								
								<!-- Formulario - Crear lista -->
								 <%= render 'form'%>
							
								

					</div>
							
					<div class="wow fadeInUp content-works "> 
							<%= render(@lists) or render partial:('empty-collection') %>
					</div>
									
		
		
	

app/views/lists/show.html.erb
	<div class="wow  content-card " style="margin-top: 0;">	
				
				<div class="row " >
					<div class="col s12"> 

						<!-- Nombre de la lista -->
						<div class="col s9 contener-texto">
											
							<h5 id="title-list" class="font-ubuntu">			
							<%=	@list.name %> </h5>

						</div>
						
						<!-- Operaciones basicas -->
						<div class="col s3"  >
						
							<!-- Volver atras -->
							<a class="tooltipped btn-floating waves-effect waves-light" href="<%= lists_path %>" data-position="bottom" data-delay="50" data-tooltip= <%=t('return')%>>	<i  class="fa fa-arrow-left" aria-hidden='true'></i>	</a>
							
							<!-- Editar nombre de la lista -->
							<a class="tooltipped  btn-floating waves-effect waves-light" href="#modalListEditName" data-position="bottom" data-delay="50" data-tooltip=<%=t('rename')%> >	<i id="edit" class="fa fa-pencil" arial-hidden='true'></i></a>
							
							<!-- Crear tarea -->
							 <a class="tooltipped  dropdown-button btn-floating waves-effect waves-light " href="" data-activates="dropdown2" data-tooltip=<%=t('create-task')%> >
							 	<i class="mdi-editor-vertical-align-bottom fa fa-plus left " arial-hidden='true'></i>
							 </a>

								<ul id="dropdown2" class="dropdown-content">
									<li><%= link_to t('task-simple'), new_list_task_simple_path(@list)  %>
									</li>
									<li><%= link_to  t('task-long'), new_list_task_long_path(@list)  %>
									</li>
									<li><%= link_to  t('task-temporary'), new_list_task_temporary_path(@list)  %>
									</li>
								</ul>

						</div>
					</div>					
				</div>
				<hr id="line"><br>

			<div class="row">
					<div class="col s12"> 
					<!-- Fecha de creación -->
						<div class="col s4">
							<b><%=t('creation-date')%>:</b> <%= @list.created_at%> 
						</div>
					<!-- Fecha última modificación  -->
					<div class="col s4">
						<b><%=t('last-update')%>:</b>
						<%= @list.last_update%>  <br>
					</div>
					
					<!-- Copiar url -->
					<div class="col s4">
						<a href="" class="chip " id="clipboard-btn" data-clipboard-text="<%= request.url %>" >
								<%=t('copy-url')%>
							<i id  class="fa fa-clipboard" aria-hidden="true"></i>
						</a>
					</div>
			</div>
			</div>
	



			<table>
				<thead> 
					<tr>
						<th width="10%"><%=t('priority')%></th>
						<th>
							<i class="fa fa-clock-o" aria-hidden='true'></i>
							<%=t('tasks-temporaries')%>
						</th>
						<tr>
					</tr>
					
				</thead>
				<tbody>

						<%= render @task_temporaries or render('empty_tasks')%>	 			
					
				</tbody>
			</table>				
			
			<table>
				<thead>
					<tr>	
						<th width="10%"><%=t('priority')%></th>					
						<th>
							<i class="fa fa-arrows-h" aria-hidden='true'></i>
							<%=t('tasks-longs')%>
						</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<%= render @task_longs or render('empty_tasks')%>
				</tbody>


			</table>
			

			<table>
				<thead>
					<tr>
						<th width="10%"><%=t('priority')%></th>
						<th>
						<i class="fa fa-file-text-o" aria-hidden='true'></i>
						<%=t('tasks-simples')%></th>
						<th></th>

					</tr>
				</thead>

				<tbody>
						<%= render @task_simples or  render('empty_tasks') %>
					
				</tbody>

			</table>

		
	</div>


		<!-- Modal  edit name -->
		  <div id="modalListEditName" class="modal bottom-sheet">
			<div class="modal-content">
			  <h4><%=t('rename-list')%></h4>
					
				<%= render 'form', list: @list%>

			</div>
			<div class="modal-footer">
			  <a class=" modal-action modal-close waves-effect waves-green btn-flat"><%=t('cancel')%></a>
		   
			</div>
		  </div>
		
	

app/views/lists/update.js.erb
 
 $('#modalListEditName').modal('close');
 $('#title-list').html("<%= @list.name %>");
 show_success_noty('success','success!')