config/routes.rb
Rails.application.routes.draw do
  
  resources :lists, :path => '' do 


  	resources :tasks ,except: [:index]

  	resources :task_temporaries, controller: 'tasks', type: 'TaskTemporary' ,except: [:show,:index]
 	resources :task_longs, controller: 'tasks', type: 'TaskLong' ,except: [:show,:index]
 	resources :task_simples, controller: 'tasks', type: 'TaskSimple' ,except: [:show,:index]
  
  end

  	
  	patch '/finish/task/:id', to: 'tasks#finish'

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	root 'lists#index'
end

app/models/task_simple.rb
class TaskSimple < Task

	belongs_to :list

	validates :state,
		presence: { message: :presence_msj },
	 	inclusion: { in: %w(Pendiente  Hecha),
	 				message: :inclusion_msj }
	

	aasm :column => 'state' do 
		state :Pendiente, :initial => true
		state :Hecha

		event :finish do 
		transitions :from => :Pendiente, :to=> :Hecha
		end
	end

	

end

app/views/task_simples/_form.html.erb
			  	<%= simple_form_for [@list,@task] do |f| %>
			  		
			  		<%=  render 'errors', task: @task %>
			  		
			  		
			      	 <%= f.input :description, as: :text, label: t('description') , input_html: {id: "description",class: "materialize-textarea", :autofocus => true} %>
			      	
			      	<label><%= t('priority') %></label>
			      	 <%= f.select :priority, Task.priorities.keys,prompt: t('select'), label: "Prioridad" %>

			    
					<%= f.input :type, :as => :hidden, :input_html => { :value => @task.type}   %>

					
					 <%= f.submit  :class => "right waves-effect blue darken-3 btn"%>
					 <% end %>

		     	<br>

app/views/task_simples/_task_simple.html.erb
			<tr id="<%=task_simple.id %>"> 
				<td> 
					<%= render partial: "partials/priorities/#{task_simple.priority.downcase}"  %>
				 </td>
				<td>
						
					<div>
					<div id="state-<%=task_simple.id%>" class='inline' >
						
						<%= render partial: "partials/states/#{task_simple.state.downcase}"  %>
					</div>
						
					<%=  best_in_place  [@list,task_simple], :description, :as => :textarea,:inner_class => 'materialize-textarea' %> </div>
					
					<div class="footer-div" >
					</div>
				</td>
				<td width="100px">
					<%= link_to  "/finish/task/#{task_simple.id}", :remote=> true , method: :patch,data: { confirm:  t('confirm')} do %>
							<i class="fa fa-check-square-o fa-lg" aria-hidden='true '></i>
					<%end %>

					<a href= "<%= edit_list_task_simple_path(id:task_simple.id,list_id:task_simple.list.url)%>" >
						<i class="fa fa-pencil fa-lg" aria-hidden='true'> </i>
					</a>
		               

					    <%= link_to list_task_simple_url(@list.url,task_simple.id), method: :delete, data: { confirm:t('confirm') },:remote => true  do %>
					 	<i class="fa fa-trash fa-lg" aria-hidden='true'></i> 
						<% end %>

				</td>
          	</tr>


     
		


						

						 	

						 	
						 	
						 

						
				

app/views/task_simples/destroy.js.erb
$('#<%=@task_simple.id %>').remove();

var n = noty({
    text	: 'success',
    layout	: 'topRight',
    theme	: 'relax',
    type	: 'success',
    animation: {
    	open: 'animated fadeIn', // Animate.css class names
        close: 'animated fadeOut', // Animate.css class names
        easing: 'swing', // unavailable - no need
        speed: 500 // unavailable - no need
    },
    maxVisible	:5,
    killer      : true
  
});

app/views/task_simples/edit.html.erb
 
<div class="wow  content-card " style="margin-top: 0;">	
	
	<a class=" btn-floating waves-effect waves-light right" href="<%= list_path(@task.list) %>"  data-delay="50" >
		<i id="edit" class="fa fa-arrow-left" aria-hidden='true'></i>
	</a>

 	<h4><%= t('edit-task')%></h4>
	<%= render 'task_simples/form' ,task:@task %>			
	
 </div> 

app/views/task_simples/new.html.erb
<div class="wow content-card " style="margin-top: 0;">	
	

	 <a class=" btn-floating waves-effect waves-light right"   data-delay="50" href="<%= list_path(@list) %>" >	<i id="edit" class="fa fa-arrow-left" aria-hidden='true'></i>	</a>
 	 <h4><%=t('create-task')%></h4>

		 <%= render 'task_simples/form'  %>			
	
 </div>