config/routes.rb
Rails.application.routes.draw do
  
  resources :lists, :path => '' do 


  	resources :tasks ,except: [:index]

  	resources :task_temporaries, controller: 'tasks', type: 'TaskTemporary' ,except: [:show,:index]
 	resources :task_longs, controller: 'tasks', type: 'TaskLong' ,except: [:show,:index]
 	resources :task_simples, controller: 'tasks', type: 'TaskSimple' ,except: [:show,:index]
  
  end

  	
  	patch '/finish/task/:id', to: 'tasks#finish'

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	root 'lists#index'
end

app/models/task_long.rb
# == Schema Information
#
# Table name: tasks
#
#  id            :integer          not null, primary key
#  description   :string           not null
#  priority      :string           not null
#  state         :string           not null
#  type          :string
#  list_id :integer
#  progress      :integer
#  date_begin    :date
#  date_end      :date
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class TaskLong < Task

	before_create :update_state
	before_update :update_state

	validates :progress, 
		presence: { message: :presence_msj },
		:inclusion => { :in => 0..100,
						message: :inclusion_msj },
		numericality: { only_integer: true, message: :numericality_msj}	

       
	validates :state,
	 	inclusion: { in: %w(Pendiente En_curso Hecha),
					message:  :inclusion_msj}
	

	aasm :column => 'state' do 
		state :Pendiente, :initial => true
		state :En_curso
		state :Hecha
		

		event :finish do 
		transitions :from => :En_curso, :to => :Hecha
		end

		event :init do 
		transitions :from => :Pendiente, :to => :En_curso 
			
		end

	end

	#valores por defecto
	after_initialize do |user|
    	self.progress ||= 0 
  	end


	def init_valid?  		
		self.progress > 0 and self.progress < 100 and may_init?
	end


	def made_valid?
		self.progress == 100 and may_finish?
	end


	def update_state
		self.init if init_valid? 
		self.finish if made_valid?	 
	end
	

	def to_s 
		super +  ", Porcentaje de avance: #{self.progress}% "
	end



end

app/views/task_longs/_form.html.erb
			 
			  	<%= simple_form_for ([@list,@task]) do |f| %>
			  		
			  		<%=  render 'errors', task: @task %>

			  		<%= f.input :type, :as => :hidden, :input_html => { :value => @task.type }  %>

			      	<%= f.input :description, as: :text, label:t('description'), input_html: {id: "description",class: "materialize-textarea"}, required: true %>
			      	
			      	<label ><%=t('priority') %> </label>
			      	 <%= f.select :priority, Task.priorities.keys, :label => "Prioridad" ,prompt: t('select') %>

			 
				
						<div class="input-field">
						 <p class="range-field">
							<%= f.input :progress ,as: :range, label:t('progress') %>
						</p>
						</div>
					


					 <%= f.submit  :class => "right waves-effect blue darken-3 btn" %>
					 <% end %>

		     		<br>

app/views/task_longs/_task_long.html.erb
			<tr id="<%=task_long.id %>">
				<td>
					<%= render partial: "partials/priorities/#{task_long.priority.downcase}"  %>
				</td>
				<td> 

					<div>
						<div id="state-<%=task_long.id%>" class="inline" >
							
							<%= render partial: "partials/states/#{task_long.state.downcase}" %>						
						</div>

						<%=  best_in_place  [@list,task_long], :description, :as => :textarea ,:inner_class => 'materialize-textarea'%> 
					</div>
					<div class="footer-div">
						

						<strong><%=t('progress') %>: </strong> <%= task_long.progress%>%


						
					</div>
 
			   </td>
			   <td width="100px">
			   		
			    		<a href= "<%= edit_list_task_long_path(@list,task_long)%>" ><i class="fa fa-pencil fa-lg" aria-hidden='true'></i> </a>
			    	 	
			    	 	 <%= link_to list_task_long_path(@list,task_long), method: :delete, data: { confirm: t('confirm') },:remote => true  do %>
			 			<i class="fa fa-trash fa-lg" aria-hidden='true'></i> 
			 			<%end%>

			   </td>
			 </tr>


						

						 	

app/views/task_longs/edit.html.erb
<div class="wow content-card " style="margin-top: 0;">	
	
	 <a class=" btn-floating waves-effect waves-light right" href="<%= list_path(@task.list) %>"  data-delay="50" >	
	 	<i class="fa fa-arrow-left" aria-hidden='true'></i>
	 </a>

 	 <h4><%= t('edit-task')%></h4>
	 <%= render partial: '/task_longs/form' ,task:@task %>			
	
 </div>

app/views/task_longs/new.html.erb
<div class="wow content-card " style="margin-top: 0;">	
	

	 <a class=" btn-floating waves-effect waves-light right"   data-delay="50" href="<%= list_path(@list) %>" >	<i  class="fa fa-arrow-left" aria-hidden='true'></i>	</a>
 	 <h4><%=t('create-task')%></h4>
	
	<%= render partial: '/task_longs/form'%>
</div>