config/routes.rb
Rails.application.routes.draw do
  
  resources :lists, :path => '' do 


  	resources :tasks ,except: [:index]

  	resources :task_temporaries, controller: 'tasks', type: 'TaskTemporary' ,except: [:show,:index]
 	resources :task_longs, controller: 'tasks', type: 'TaskLong' ,except: [:show,:index]
 	resources :task_simples, controller: 'tasks', type: 'TaskSimple' ,except: [:show,:index]
  
  end

  	
  	patch '/finish/task/:id', to: 'tasks#finish'

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	root 'lists#index'
end

app/models/task_temporary.rb
# == Schema Information
#
# Table name: tasks
#
#  id            :integer          not null, primary key
#  description   :string           not null
#  priority      :string           not null
#  state         :string           not null
#  type          :string
#  list_id :integer
#  progress      :integer
#  date_begin    :date
#  date_end      :date
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class TaskTemporary < Task
   
	validates :description,
	length: { maximum: 256, message: :lenght_msj }


	validates :state,
	 	inclusion: { in: %w(Pendiente Hecha Expirada),
	 				message:  :inclusion_msj }
	
	validates :date_begin, presence: { message: :presence_msj }
	validates :date_end, presence: { message: :presence_msj }
	
	validates_date :date_begin, :before =>   lambda{|m| m.date_end},before_message: :before_msj
   	validates_date :date_end, :after =>   lambda{|m| m.date_begin}, after_message: :after_msj
   	validates_date :date_end, :on_or_after => lambda{ Date.current }, on_or_after_message: :after_act_msj

	

	aasm :column => 'state' do 
		state :Pendiente, :initial => true
		state :Hecha
		state :Expirada

		event :finish do 
		transitions :from => :Pendiente, :to=> :Hecha
		end

		event :expired do 
		transitions :from => :Pendiente, :to=> :Expirada
		end
	end


	#mostrar solo tareas dentro de la fecha válida antes de que expire 
	self.default_scope { where('date_end > ?', Date.current ) }

	def self.expired
		where('date_end <= ? ', Date::current)
	end

	def self.change_state
		update_all( state:'Expirada')
	end

	def to_s 
		super +", Fecha inicio: #{self.date_begin}, Fecha de finalizacion: #{self.date_end}"
	
	end


end

app/views/task_temporaries/_form.html.erb
 	<%= simple_form_for ([@list,@task]) do |f| %>
			  		
			  		<%=  render 'errors', task: @task %>
			  		
			  		<%= f.input :type, :as => :hidden, :input_html => { :value => @task.type }  %> 
			  		
			 	  	<%= f.input :description, as: :text, label:t('description'), input_html: {id: "description",class: "materialize-textarea"} %>
			      	<label ><%=t('priority') %> </label>
			      	<%= f.select :priority, Task.priorities.keys,prompt:t('select'), label: "Prioridad" %>


					<%= f.input :date_begin ,as: :string,label: t('date-begin'),input_html:{ class: 'datepicker',
						data_value: '' } %>


					<%= f.input :date_end ,as: :string,label: t('date-end'),input_html:{ class: 'datepicker',
							data_value: ''} %>



					
					 <%= f.submit  :class => "right waves-effect blue darken-3 btn" %>
					 <% end %>
					<br>

app/views/task_temporaries/_task_temporary.html.erb
		
		<tr id="<%= task_temporary.id%>">
				<td >
					<%= render partial: "partials/priorities/#{task_temporary.priority.downcase}"  %>
				</td>
				<td width="80%">

					<div>
						<div id="state-<%=task_temporary.id%>" class="inline" >
							
							<%= render partial: "partials/states/#{task_temporary.state.downcase}" %>						
						

						</div>

					  <%=  best_in_place  [@list,task_temporary], :description, :as => :textarea ,:inner_class => 'materialize-textarea'%> </div>
					<div class="footer-div">
												
						 <strong ><%= t('date-begin')%>:</strong> <%= task_temporary.date_begin %>
					
						 <strong ><%= t('date-end')%>: </strong> <%= task_temporary.date_end %>		    
			    
			 
					</div>
				
				</td>

				<td width="100px">

						<%= link_to  "/finish/task/#{task_temporary.id}", :remote=> true , method: :patch,data: { confirm: t('confirm')} do %>
							<i class="fa fa-check-square-o fa-lg" aria-hidden='true '></i>
						<%end %>

						<a href= "<%= edit_list_task_temporary_path(@list,task_temporary)%>" >
							<i class="fa fa-pencil fa-lg" aria-hidden='true'></i>
						</a>
						 <%= link_to list_task_temporary_path(@list,task_temporary), method: :delete, data: { confirm: t('confirm') },:remote => true  do %>
				 		<i class="fa fa-trash fa-lg" aria-hidden='true'></i> 
						<% end %>

				</td>
				
		</tr>       
          
			   

			 

			

      

app/views/task_temporaries/edit.html.erb
<div class="wow content-card " style="margin-top: 0;">	
	

	 <a class=" btn-floating waves-effect waves-light right" href="<%= list_path(@task.list) %>"  data-delay="50" >	
	 	<i  class="fa fa-arrow-left" aria-hidden='true'></i>
	  </a>
 	 <h4><%=t('edit-task')%> </h4>

		 <%= render partial: '/task_temporaries/form' ,task:@task %>			
	
 </div>

app/views/task_temporaries/new.html.erb
<div class="wow  content-card " style="margin-top: 0;">	
	

	 <a class=" btn-floating waves-effect waves-light right"   data-delay="50" href="<%= list_path(@list) %>" >	
	 	<i class="fa fa-arrow-left" aria-hidden='true'></i>
	 </a>
 	 <h4>Crear Tarea</h4>
	
	<%= render partial: '/task_temporaries/form'%>
</div>